version: 2
updates:
  # Enable version updates for bun
  - package-ecosystem: 'bun'
    # Look for `package.json` and `bun.lockb` files in the `root` directory
    directory: '/'
    # Check the registry for updates every week
    schedule:
      interval: 'weekly'

  # Enable version updates for composer
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: '/'
    schedule:
      interval: 'weekly'
